version: 2.1
# tokutei-data-platformのやつをコピーして試してみる
jobs:
  build:
    docker:
      - image: circleci/python:3.8.1
    steps:
      - checkout
      - run:
          name: Install Python Dependencies
          command: |
            pip install --user -r requirements.txt
      - run:
          name: Run tests
          command: python -m pytest
